//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame
{
    
    
    public partial class MyGameStates
    {
        
        public static int StateA = 1;
        
        public static int StateB = 2;
        
        public static int StateC = 4;
    }
}
